### ISSUE TITLE
Release plugin to Bintray

### ISSUE THREAD

**Issue by rlovtangen** [grails-plugins/grails-cache-ehcache#25]
Plugin source is updated to Grails 3, but there is no version released to Bintray yet.
A milestone or release candidate would be great, so it would be easier to try the plugin with Grails 3 and give feedback before a GA version.

**Comment by graemerocher** [comment]
@rlovtangen I believe @colinharrington will be taking this on soon. Thanks for the report

**Comment by rlovtangen** [comment]
👍

**Comment by kschmit90** [comment]
+1 for this, I'm unable to move forward with an upgrade due to this dependency not being available.

**Comment by rlovtangen** [comment]
@kschmit90: This is holding back upgrade of a lot of applications for us too, so I released a custom build to my Bintray repo: https://bintray.com/rlovtangen/plugins/cache-ehcache/2.0.0.R-M1
You can try it out while waiting for an official release. It's just the latest source with this small change: https://github.com/rlovtangen/grails-cache-ehcache/commit/e552466019c58596ab038a1bc159670896c68445
Tested with a clean Grails 3.1.9 project, worked fine.

**Comment by kschmit90** [comment]
@rlovtangen thx, I asked around on the slack channel and ended up adding back the

maven { url "https://repo.grails.org/grails/core" } which I normally remove and use internal repos

and added compile 'org.grails.plugins:cache-ehcache:2.0.0.BUILD-SNAPSHOT' as a dependency.

**Comment by ColinHarrington** [comment]
There is a snapshot version available.  Can you guys please give it a whirl and report any issues before we publish 2.0.0

**Comment by rlovtangen** [comment]
Works fine for me when running `bootRun`, but I'm not able to run integration tests. Created issue https://github.com/grails-plugins/grails-cache-ehcache/issues/27

**Comment by rlovtangen** [comment]
Have been using the snapshot version in production for a while now. Could we have a M1 or RC1 release so that our build becomes reproducible?

**Comment by rlovtangen** [comment]
In Grails 3.2 I need to downgrade ehcache to an older version than comes with Grails 3.2.x to get this plugin to work. As I'm not sure of the potential implications of that, it's holding me back from upgrading to  Grails 3.2.x. See #26

**Comment by snimavat** [comment]
Any progress here ? looks like still there's no version available on bintray

**Comment by jameskleeh** [comment]
Coming soon

**Comment by danduke** [comment]
Trying to plan some releases around this; any guess as to what "soon" means?  Even "definitely this quarter" or "maybe the the end of year" would be helpful to know for a lot of people I think!  Thanks!

**Comment by jameskleeh** [comment]
@danduke An M1 of this plugin was released. As far as the GA, I would guess sometime this quarter, depending on feedback. Any feedback now would be appreciated.

**Comment by danduke** [comment]
@jameskleeh I'm trying to evaluate this now (in grails 3.2.9, but with the gorm version bumped to 6.1.3; tell me if that shouldn't work for some reason!) but I can't find a way to configure caches in plugins.  It's also unclear how we could configure caches at runtime, based on other evaluated configuration items.  

I did see on the customization/index.adoc that I can define my own ehcacheConfiguration bean.  Is that the only way to load configuration from multiple sources?  Ideally, I'd like to have something similar to the old-style *CacheConfig.groovy files, where each plugin could provide its own cache configuration, all of which gets loaded and combined at runtime, but can't find any supported way to do that now.

Thanks!

**Comment by jameskleeh** [comment]
@danduke It should work with 3.2.9 and GORM 6.1.x. I found no way in Ehcache to load config from a configuration file, so the `*CacheConfig.groovy` way is not an option. 

As far as having separate config in plugins, you would have to research if the Ehcache API supports that. Perhaps you can load in multiple XML files.

**Comment by danduke** [comment]
Sorry for the extremely delayed response; non-grails-3 work (and vacation, yay!) got in the way of working on this.  I'm back on this now, and am working on a way to load multiple *CacheConfig (or whatever) files into a single configuration during application startup.  I have that working in a simple test case, and am trying to integrate into a larger application now.

I'm hitting a different problem, and I can open a different issue for it but figured maybe you'd just know offhand what the cause is.  Our codebase makes pretty heavy use of plugins (mostly in-house, but some public as well), some of which provide domain objects.  As part of the attempt to use this plugin, I'm of course having to upgrade to gorm 6.1.x.  Unfortunately, it appears that I also have to upgrade *every* plugin that provides domain objects to 6.1.x as well.  Obviously, this is a pain, and not even necessarily possible for 3rd party plugins.  Is this intended, or expected?  If not, I can open a separate issue with more details or just comment here; I'm good with whatever you prefer.

**Comment by danduke** [comment]
https://stackoverflow.com/questions/44635366/is-it-possible-to-have-different-gorm-versions-in-plugins-within-a-grails-3-appl in case anybody watching this can provide comments.

**Comment by danduke** [comment]
I'm going to try to offer some feedback here that may be useful to the developers, or to others using this plugin.  Unfortunately sharing actual code is challenging from my company (they're weird about "developed here, stays here" without a painfully long legal release process) but I think I can at least provide some conceptual descriptions of what worked well for me.

We have multiple grails 2 applications that we're just now upgrading to grails 3.  We make heavy  use of in-house plugins, and limited use of third party plugins.  Many of these plugins define their own domain objects, and even more define their own caches.  

Per my stackoverflow post above, we did find it to be necessary to upgrade *every* plugin that provides domain objects to have the same version of GORM.  This is problematic, but not specific to the ehcache plugin.  Still, it's good to be aware of.  The warning you get when starting with a different GORM version in some plugin is not particularly descriptive.

The biggest problem that I had with this plugin as-is is that there is no more way to specify cache configuration in more than one place.  Fortunately, it's not that hard to add this capability.  It would be pretty easy to add this to the plugin itself too, if anybody (who is legally allowed to by their company) wanted to!  The steps that I took are encapsulated in my own plugin, but are basically:
* loadBefore cache plugin in my plugin descriptor
* doWithSpring block of my plugin descriptor calls a utility method, which does the following:
* get the current classloader, and use it to load an XML resource that is an ehcache config template file (has comment blocks where the persistence block goes, and where the individual caches go.  My setup does not require configuring a default template, but you could easily do that too.)
* Use a PathMatchingResourcePatternResolver to find all CacheConfig files, like resolver.getResources("classpath*:some/package/**/*CacheConfig.class")
* I basically used a StreamingMarkupBuilder to convert each "cache" element in a cache config file to XML, and inserted that into my template, then saved the template to a known location.
  * It would be nicer to implement something like Burt had implemented in the previous version of this plugin to actually parse the config file using a Builder, so that it's not order-dependent.  However, that is fancier than I needed since I have a lot of caches but all I really wanted was expiry and resource blocks.
* Write the template to a known location (java.io.tmpdir certainly works) and have that configured for where this plugin will read the file, when configuring its caches.

It's obviously a lot easier to do this for a single situation (my own) than to do it generically in this plugin.  Maybe it's not worth putting into the plugin, but I think that having some way to configure caches in third party plugins is pretty important, if this is supposed to be used in any production environment.  

You asked for feedback, and mine is:
* Highest priority is probably not specific to this plugin: different versions of GORM across plugins preventing app startup is almost a non-starter.  I'd love for somebody to explain to me that I'm wrong in that, but from what I've read, GORM decorating is done at compile-time now, rather than runtime, so it kind of makes sense that versions would be compiled into a jar-based plugin.  I don't see any good fix to that but it's a real problem for having external dependencies.
* Highest priority that you could actually address in this plugin is ability to specify some sort of cache config in individual plugins, which gets combined during startup.  I've outlined one option above at a fairly high level.  It works but is not particularly elegant.
* Lower priorities is to make the implementation of external configuration more elegant.  A content-aware builder is definitely more elegant than just parsing files into XML.

**Comment by danduke** [comment]
Just revisiting old issues...any updates on this?

**Comment by graemerocher** [comment]
A release has been issued http://plugins.grails.org/plugin/grails/cache-ehcache see 3.3.0.M1

@jameskleeh anything holding back GA?

**Comment by jameskleeh** [comment]
Not that I'm aware of

**Comment by sbglasius** [comment]
Then why has there never been a GA release?

**Comment by puneetbehl** [comment]
I could plan a release of 3.0.0 however the plugin still on JDK 7 so I am not sure if it would be possible to use the same with Travis. I believe we should move to minimum of JDK8. Please let me know of your thoughts.
